[package]
name = "viper"
version = "0.1.0"
description = "High-level interface to Viper"
authors = ["Federico Poli <federpoli@gmail.com>"]
license = "MPL-2.0"
readme = "README.md"

[dependencies]
log = { version = "0.4", features = ["release_max_level_info"] }
error-chain = "0.12.0"
viper-sys = { path = "../viper-sys" }
jni = { version = "0.17.0", features = ["backtrace", "invocation"] }
uuid = { version = "0.7", features = ["v4"] }
serde = { version = "1.0" }
serde_derive = { version = "1.0" }

[dev-dependencies]
lazy_static = "1.0"
env_logger = "0.5.13"
bencher = "0.1.5"

[[bench]]
name = "bench_program"
harness = false
