[package]
authors = ["Federico Poli <federpoli@gmail.com>"]
description = "Translation of MIR into Viper"
name = "prusti-viper"
readme = "README.md"
license = "MPL-2.0"
version = "0.1.0"
edition = "2018"

[lib]
doctest = false # we have no doc tests

[dependencies]
log = { version = "0.4", features = ["release_max_level_info"] }
viper = { path = "../viper" }
prusti-interface = { path = "../prusti-interface" }
prusti-common = { path = "../prusti-common" }
prusti-specs = { path = "../prusti-specs" }
prusti-server = { path = "../prusti-server" }
num-traits = "0.2.6"
itertools = "0.9.0"
pretty_assertions = "0.5.1"
regex = "1.3.9"
serde = "1.0"
typed-arena = "*"

[dev-dependencies]
lazy_static = "1.4.0"
