[package]
name = "prusti"
version = "0.2.0"
authors = ["Vytautas Astrauskas <vastrauskas@gmail.com>"]
edition = "2018"
default-run = "prusti-rustc"

[lib]
test = true # we have unit tests
doctest = false # but no doc tests

[[bin]]
name = "prusti-rustc"
test = false # we have no unit tests
doctest = false # and no doc tests

[[bin]]
name = "prusti-driver"
test = false # we have no unit tests
doctest = false # and no doc tests

[dependencies]
env_logger = "0.7.1"
prusti-contracts = { path = "../prusti-contracts", features = ["prusti"] }
prusti-contracts-internal = { path = "../prusti-contracts-internal" }
prusti-specs = { path = "../prusti-specs" }
prusti-env-utils = { path = "../prusti-env-utils" }
prusti-macros = { path = "../prusti-macros" }
prusti-interface = { path = "../prusti-interface" }
prusti-viper = { path = "../prusti-viper" }
compiletest_rs = "0.5.0"
log = "0.4"
log-derive = "0.4.0"
regex = "1.3.9"

[build-dependencies]
prusti-env-utils = { path = "../prusti-env-utils" }