[package]
authors = ["Julian Dunskus <julian.dunskus@gmail.com>"]
description = "Server-side logic & handling for Prusti"
name = "prusti-server"
license = "MPL-2.0"
version = "0.1.0"

[lib]
test = true # we have unit tests
doctest = false # but no doc tests

[[bin]]
name = "prusti-server-driver"
path = "src/driver.rs"
test = false
doctest = false

# TODO: caret versions to replace "= x.y.z" requirements and updates once compiler updated
[dependencies]
log = { version = "0.4", features = ["release_max_level_info"] }
viper = { path = "../viper" }
prusti-common = { path = "../prusti-common" }
env_logger = "0.5.13"
clap = "2.33.3"
bincode = "1.0"
futures = "0.1.24"
reqwest = "0.9"
warp = "= 0.1.11"
tokio = "= 0.1.11"
# indirect dependencies we have to enforce earlier versions of because of our old compiler version (technically, these are enforced via Cargo.lock, but that feels fragile to me)
urlencoding = "= 1.0"
utf-8 = "= 0.7.4"
percent-encoding = "= 1.0.1"
num_cpus = "1.8.0"
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
lazy_static = "1.0"
