[package]
name = "prusti-tests"
version = "0.2.0"
authors = ["Federico Poli <federpoli@gmail.com>"]
edition = "2018"

[dev-dependencies]
compiletest_rs = "0.7.0"
prusti-server = { path = "../prusti-server" }
prusti-launch = { path = "../prusti-launch" }
prusti = { path = "../prusti" }

[package.metadata.rust-analyzer]
# This crate uses #[feature(rustc_private)]
rustc_private = true
