[package]
name = "systest"
version = "0.1.0"
build = "build.rs"

[build-dependencies]
jni-gen = { path = ".." }
error-chain = "0.12.0"
env_logger = "0.8.2"
ureq = "1.5.2"
tempdir = "0.3.5"

[dependencies]
error-chain = "0.12.0"
jni = { version = "0.19", features = ["invocation"] }
