name: Test coverage

on:
  push:
    branches: 'master'

env:
  RUST_BACKTRACE: 1
  PRUSTI_ASSERT_TIMEOUT: 60000
  # The following are necessary for profiling (see https://github.com/mozilla/grcov)
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests #-Cpanic=abort
  RUSTDOCFLAGS: -Cpanic=abort

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Set up the environment
        run: python x.py setup
      - name: Build with cargo
        run: python x.py build --all --verbose
      - name: Run cargo tests, enabling debug dumps
        run: python x.py test --all --verbose
        env:
          PRUSTI_DUMP_DEBUG_INFO: true
          PRUSTI_DUMP_DEBUG_INFO_DURING_FOLD: true
          PRUSTI_DUMP_VIPER_PROGRAM: true
      - name: Check prusti-contracts
        run: |
          cd prusti-contracts-test/
          cargo build
      - name: Collect coverage
        run: |
          curl -sL https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
          zip -q0 ccov.zip $(find . \( -name "prusti*.gc*" -or -name "viper*.gc*" -or -name "jni_gen*.gc*" \) -print)
          ./grcov ccov.zip --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./lcov.info
