name: Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

env:
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
    - name: Add Java JDK to the library path
      run: echo "::set-env name=LD_LIBRARY_PATH::"$(dirname "$(find "$JAVA_HOME" -name "libjvm.so")")""
    - name: Setup Viper
      run: |
        wget -q 'http://viper.ethz.ch/downloads/ViperToolsNightlyLinux.zip'
        unzip ViperToolsNightlyLinux.zip -d viper_tools
        rm ViperToolsNightlyLinux.zip
        echo "::set-env name=VIPER_HOME::$(pwd)/viper_tools/backends/"
        echo "::set-env name=Z3_EXE::$(pwd)/viper_tools/z3/bin/z3"
    - name: Install system dependencies for Prusti
      run: sudo apt-get install -y build-essential pkg-config gcc libssl-dev
    - name: Build with cargo
      run: |
        cd new
        rustup component add rustfmt
        rustup component add rust-src
        rustup component add rustc-dev
        rustup component add llvm-tools-preview
        cargo build --all --verbose
    - name: Run cargo tests
      run: cd new && cargo test --all --verbose
      env:
        RUST_BACKTRACE: 1
        RUST_TEST_THREADS: 1
        PRUSTI_ASSERT_TIMEOUT: 60000
    - name: Check formatting
      run: |
        cd new
        rustup component add rustfmt
        cargo fmt -- --check
    - name: Check prusti-contracts
      run: |
        cd new/prusti-contracts-test/
        cargo build
